@startuml dev
skinparam defaultTextAlignment center
skinparam linetype polyline
skinparam Dpi 300

skinparam monochrome true
skinparam shadowing false
skinparam classFontName Arial
' card lab1 as "Whether keep field"

' card lab2 as "The augmentation"

' card lab3 as "The datasize"

' card lab4 as "The augmented prediction"


rectangle data as "
**Current Dataset**
//Labelled Cases//"

card train as "Train Set"

together {
card test as "Validation Set"

card model as "Models"
}
card output as "The Final Model"

data -r-> train : 80%

data -r-> test : 20%

train --> model : "10 epochs"

test -u-> model : "Evaluation"

model --> output : "The highest F1-score"

@enduml
