@startuml text_aug
' skinparam defaultTextAlignment center
skinparam linetype polyline
skinparam Dpi 300
skinparam monochrome true
skinparam shadowing false
skinparam classFontName Arial
together {
    rectangle origin as "
    **Field A**: Description A.
    ---
    **Field B**: Description B.
    ---
    **Field C**: Description C.
    "

    rectangle aug as "
    **Field C**: Description C.
    ---
    **Field A**: Description A.
    ---
    **Field B**: Description B.
    "
}

together {
    card text_ori as "Field A: Description A. Field B: Description B.
     Field C: Description C."

    card text_aug as "Field C: Description C. Field A: Description A.
     Field B: Description B."
}

' together {
' card text_ori_no as "Description A. Description B.
'  Description C."
' card text_aug_no as "Description C. Description A.
'  Description B."
' }

origin -r-> aug : "Randomly shuffle the order of fields with their descriptions"


origin -d-> text_ori : "Convert into a text string"

aug -d-> text_aug : "Convert into a text string"


' origin -d-> text_ori_no : "Without field"

' aug -d-> text_aug_no : "Without field"

' text_ori -[hidden]-> text_ori_no
' text_aug -[hidden]-> text_aug_no
@enduml
